import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ['thai']
});

export const metadata: Metadata = {
  title: "ข่าวสารประเทศไทย",
  description: "Generated by NatchaLatte Official",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex justify-center items-center ${kanit.className}`}>{children}</body>
    </html>
  );
}
